<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="3675" started-at="2022-03-09T16:06:19 IST" finished-at="2022-03-09T16:06:23 IST">
    <groups>
    </groups>
    <test name="Delete Customer API Test" duration-ms="2681" started-at="2022-03-09T16:06:19 IST" finished-at="2022-03-09T16:06:22 IST">
      <class name="com.w2a.testcases.DeleteCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.w2a.testcases.DeleteCustomerTest@434a63ab]" name="setUp" is-config="true" duration-ms="511" started-at="2022-03-09T16:06:18 IST" finished-at="2022-03-09T16:06:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="deleteCustomer(java.util.Hashtable)[pri:0, instance:com.w2a.testcases.DeleteCustomerTest@434a63ab]" name="deleteCustomer" duration-ms="2599" started-at="2022-03-09T16:06:19 IST" data-provider="data" finished-at="2022-03-09T16:06:22 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_GN1t2FBIs7YE6u}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ID key is not present in the JSON response expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ID key is not present in the JSON response expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.w2a.testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.w2a.testcases.DeleteCustomerTest@434a63ab]" name="tearDown" is-config="true" duration-ms="1" started-at="2022-03-09T16:06:23 IST" finished-at="2022-03-09T16:06:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.w2a.testcases.DeleteCustomerTest -->
    </test> <!-- Delete Customer API Test -->
    <test name="Create Customer API Test" duration-ms="3675" started-at="2022-03-09T16:06:19 IST" finished-at="2022-03-09T16:06:23 IST">
      <class name="com.w2a.testcases.CreateCustomerTest">
        <test-method status="FAIL" signature="validateCreateCustomerAPIWithInValidSecretKey(java.util.Hashtable)[pri:0, instance:com.w2a.testcases.CreateCustomerTest@7e7be63f]" name="validateCreateCustomerAPIWithInValidSecretKey" duration-ms="2530" started-at="2022-03-09T16:06:19 IST" data-provider="data" finished-at="2022-03-09T16:06:21 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=java@way2automation.com, name=Rahul Arora, description=Adding the Second customer in framework}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.w2a.testcases.CreateCustomerTest.validateCreateCustomerAPIWithInValidSecretKey(CreateCustomerTest.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPIWithInValidSecretKey -->
        <test-method status="PASS" signature="validateCreateCustomerAPIWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.w2a.testcases.CreateCustomerTest@7e7be63f]" name="validateCreateCustomerAPIWithValidSecretKey" duration-ms="966" started-at="2022-03-09T16:06:22 IST" data-provider="data" finished-at="2022-03-09T16:06:23 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=corporate@way2automation.com, name=Raman Arora, description=Adding the Third Customer in Framework}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPIWithValidSecretKey -->
        <test-method status="PASS" signature="validateCreateCustomerAPIWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.w2a.testcases.CreateCustomerTest@7e7be63f]" name="validateCreateCustomerAPIWithValidSecretKey" duration-ms="984" started-at="2022-03-09T16:06:22 IST" data-provider="data" finished-at="2022-03-09T16:06:23 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=ishita@way2automation.com, name=Ishita Arora, description=Adding the forth Customer in framework}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPIWithValidSecretKey -->
        <test-method status="PASS" signature="validateCreateCustomerAPIWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.w2a.testcases.CreateCustomerTest@7e7be63f]" name="validateCreateCustomerAPIWithValidSecretKey" duration-ms="956" started-at="2022-03-09T16:06:22 IST" data-provider="data" finished-at="2022-03-09T16:06:23 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=java@way2automation.com, name=Rahul Arora, description=Adding the Second customer in framework}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPIWithValidSecretKey -->
      </class> <!-- com.w2a.testcases.CreateCustomerTest -->
    </test> <!-- Create Customer API Test -->
  </suite> <!-- Suite -->
</testng-results>
